---
- name: Onboard new APP
  hosts:
    - localhost
  gather_facts: false
  tasks:
    - name: configure job templates
      ansible.builtin.include_role:
        name: redhat_cop.controller_configuration.job_templates

    - name: configure workflows
      ansible.builtin.include_role:
        name: redhat_cop.controller_configuration.workflow_job_templates
